services:
  db:
    image: mysql:8.4.2
    container_name: modulo5
    environment:
      MYSQL_DATABASE: modulo5
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - modulo5_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql 

volumes:
  modulo5_data: